services:
  db:
    build: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: oodbu
      POSTGRES_PASSWORD: oodbpasswd
      POSTGRES_DB: oodb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5432"] # setup db will create a tmp server that doesn't open any tcp ports
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    build: openolat
    environment:
    - DATABASE_URL="jdbc:postgresql://db:5432/oodb"
    - DATABASE_USERNAME=oodbu
    - DATABASE_PASSWORD=oodbpasswd
    ports:
      - "8088:8088"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-Ssf", "http://localhost:8088"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
